spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.81.129:3306/guli_oms?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:/mapper/oms/*.xml
server:
  port: 11000

